IM_Sys/DoctorApp/urls.py
from django.urls import path
from . import views

app_name = 'DoctorApp'

urlpatterns = [
    path("index/",views.personal_info,name="doctor_index"),#首页
    path("change_pwd/",views.change_pwd,name="change_pwd"),#修改密码
    path("online_consult/",views.online_consult,name="online_consult"),#线上咨询 治疗
    path("register/",views.register,name="register"),#预约管理
    path("answer1/",views.answer1,name="answer1"),
    path('add_prescription/', views.add_prescription, name='add_prescription'),
    path('save_prescription/', views.save_prescription, name='save_prescription'),
# path('ask_medicine/', views.ask_medicine, name='ask_medicine'),
path("answer2/", views.answer2, name="answer2"),

]

IM_Sys/IM_Sys/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from IM_Sys.views import home,login,register,test,logout,error

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home,name="home"),#首页
    path("login/",login,name="login"),#登录
    path("register/",register,name="register"),#注册
    path("logout/",logout,name="logout"),
    path("user/",include("UserApp.urls")),#用户
    path("doctor/",include("DoctorApp.urls")),#医生
    path("admin_sys/",include("adminApp.urls")),#管理员
    path("blog/",include("BlogApp.urls")),#博客
    path("error/",error,name="error"),
    path("test/",test,name="test"),
]

IM_Sys/UserApp/urls.py
from django.urls import path
from . import views

app_name = 'UserApp'

urlpatterns = [
    path("index/",views.personal_info,name="home"),#用户首页
    # path("home/",views.home,name="home"),#用户首页
    path("user_basic/",views.user_basic,name="user_basic"),#个人基本信息
    path("personal_manage/",views.personal_manage,name='personal_manage'),#个人健康档案管理
    path("personal_add/",views.personal_add,name="personal_add"),#个人健康档案添加
    path("family_manage/",views.family_manage,name='family_manage'),#家庭健康档案管理
    path("family_add/",views.family_add,name="family_add"),#家庭健康档案添加
    path("change_pwd/",views.change_pwd,name="change_pwd"),#修改密码
    path("blog/",views.blog,name="blog"),#论坛增删查改
    path("like_post/",views.like_post,name="like_post"),#点赞帖子
    path("blog_details/",views.blog_details,name="blog_details"),#论坛详情
    path("comment/",views.comment,name="comment"),#评论
    path("news/",views.news,name="news"),#新闻
    path("news_details/",views.news_details,name="news_details"),#新闻详情
    path("user_register/",views.user_register,name="user_register"),#我的预约
    path("register_online/",views.register_online,name="register_online"),#线上挂号
    path("online_consult/",views.online_consult,name="online_consult"),#线上咨询
    path("my_online_consult/",views.my_online_consult,name="my_online_consult"),#我的线上咨询
    path("answer/",views.answer,name="answer"),
    path('add_prescription/', views.add_prescription, name='add_prescription'),
    path('save_prescription/', views.save_prescription, name='save_prescription'),
path('get_doctors_by_department/<int:department_id>/', views.get_doctors_by_department, name='get_doctors_by_department'),
]

IM_Sys/DoctorApp/models.py
from django.db import models
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "IM_Sys.IM_Sys.settings")
# Create your models here.


class Doctor(models.Model):#
    uid = models.AutoField(primary_key=True)  # 用户编号
    doctor_name = models.CharField(max_length=20)  # 用户名
    keshi = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=20)  # 邮箱
    password = models.CharField(max_length=20)  # 密码
    doctor_sex = models.CharField(max_length=20)  # 性别
    doctor_age = models.IntegerField()  # 年龄
    profile=models.TextField(default="/static/img/profile-img.jpg")#头像
    title = models.CharField(max_length=20)  # 职称	varchar
    deid = models.ForeignKey("Department", on_delete=models.CASCADE,null=True)  # 所属科室	varchar
    hospital = models.CharField(max_length=20)  # 所属医院	varchar
    role = models.CharField(max_length=20)  # 角色
    good_at=models.CharField(max_length=255,null=True)  # 擅长领域
    states=models.IntegerField(default=0)#权限
    c_time = models.DateTimeField(auto_now_add=True)  # 注册时间




class Department(models.Model):#所属科室
    id=models.AutoField(primary_key=True)
    d_name= models.CharField(max_length=255)#科室名称
    introduce=models.TextField(null=True)#科室介绍


class Recipe(models.Model):#处方
    recipe_id = models.AutoField(primary_key=True)  # 处方编号
    # d_id=models.ForeignKey("Doctor", on_delete=models.CASCADE,null=True)#所述医生编号
    # department = models.CharField(max_length=20)  # 科室
    date = models.DateTimeField(auto_now_add=True)  # 日期
    # u_id=models.ForeignKey("UserApp.User", on_delete=models.CASCADE,null=True)#用户编号
    # user_name = models.CharField(max_length=20)  # 病人姓名
    # user_sex = models.CharField(max_length=20)  # 性别
    # user_age = models.CharField(max_length=20)  # 年龄
    symptom = models.CharField(max_length=255)  # 症状
    diagnose = models.CharField(max_length=255)  # 诊断
    Rp = models.TextField()  # 药方
    c_time = models.DateTimeField(auto_now_add=True)  # 注册时间
class Consult(models.Model):#线上咨询信息
    c_id=models.AutoField(primary_key=True)#咨询信息编号
    d_id=models.ForeignKey("Doctor", on_delete=models.CASCADE)#医生编号
    u_id=models.ForeignKey("UserApp.User", on_delete=models.CASCADE)#用户编号
    r_id=models.ForeignKey("Recipe", on_delete=models.CASCADE,null=True)#处方编号
    # conent= models.TextField()  #内容
    target=models.TextField(null=True)#咨询目标
    howlong=models.TextField(null=True)#持续时间
    drugs=models.TextField(null=True)#药品
    status=models.IntegerField(null=True,default=0)#状态 0申请 1已回复
    c_time = models.DateTimeField(auto_now_add=True)  # 创建时间

class Register(models.Model):#挂号信息
    r_id=models.AutoField(primary_key=True)#挂号信息编号
    d_id=models.ForeignKey("Doctor", on_delete=models.CASCADE)#预约医生编号
    u_id=models.ForeignKey("UserApp.User", on_delete=models.CASCADE)#预约用户编号
    r_type=models.CharField(max_length=20,null=True) #挂号类型
    date=models.DateTimeField(null=True)#挂号时间
    s_time=models.CharField(max_length=20)#预约时间开始
    end_time=models.CharField(max_length=20)#预约时间结束
    status= models.TextField(default="0")  #状态
    c_time = models.DateTimeField(auto_now_add=True)  # 创建时间

IM_Sys/DoctorApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator

from UserApp.models import User, Health_doc, Relative, Userinfo, PEinfo, Visit, CrawledContent
from django.http import HttpResponseRedirect
from DoctorApp.models import Doctor, Register, Department, Consult,Recipe
from BlogApp.models import News, Post, Comment
import json
from django.views.decorators.csrf import csrf_exempt
from py2neo import Graph, Node, Relationship
# from django.http import HttpResponse,JsonResponse

from django.http import HttpResponseRedirect,JsonResponse
def login_role_auth(fn):
    def wrapper(request,*args,**kwargs):
        if request.session.get('is_login', False) and request.session.get('user_type')=="/doctor" :
            return fn(request,*args,*kwargs)
        else:
            # 获取用户当前访问的url，并传递给/user/login/
            next = request.get_full_path() 
            request.session["is_login"]=False
            red = HttpResponseRedirect("/login/")
            return red
    return wrapper

@login_role_auth
def change_pwd(request):#个人中心 修改密码
    massage={"info":''}
    if request.method=="POST":
        old_pwd=request.POST.get("old_pwd")
        new_pwd=request.POST.get("new_pwd")
        if old_pwd==new_pwd:
            massage={"info":'新密码和原密码一致',"res":0}
        else:
            user=Doctor.objects.filter(uid=request.session.get('uid')).first()
            if user.password!=old_pwd:
                massage={"info":'原密码不正确',"res":1}
            else:
                user.password=new_pwd
                user.save()
                massage={"info":'密码修改成功',"res":2}
        return JsonResponse(massage) 
    else:
        return render(request,"doctor_passwd.html",massage)
def personal_info(request):#个人中心 个人信息
    if request.method=="GET":
        departments=Department.objects.all()
        doctor=Doctor.objects.filter(uid=request.session.get('uid')).first()
        return render(request,"doctor_index.html",{"user":doctor,'departments':departments})
    elif request.method=="POST":
        doctor_name=request.POST.get('doctor_name')
        uid=request.session.get('uid')
        email=request.POST.get('email')
        doctor_sex=request.POST.get('doctor_sex')
        doctor_age=request.POST.get('doctor_age')
        title=request.POST.get('title')
        hospital=request.POST.get('hospital')
        profile=request.POST.get('profile1')
        # role=request.POST.get('role')
        deid=request.POST.get('deid')
        good_at=request.POST.get('good_at')
        d=Doctor.objects.filter(uid=uid).first()
        d.doctor_name=doctor_name
        d.email=email
        d.doctor_sex=doctor_sex
        d.doctor_age=doctor_age
        d.title=title
        d.deid=Department.objects.filter(id=deid).first()
        d.hospital=hospital
        # d.role=role
        if profile:

            d.profile=profile
        d.good_at=good_at
        d.save()
        return redirect("/doctor/index/")
        

def online_consult(request):#线上咨询
    cid=request.GET.get('cid')
    type=request.GET.get('type')
    if request.method=="GET" and not cid:
        consults=Consult.objects.filter(d_id=request.session.get("uid"))
        return render(request,"online_manage.html",{'consults':consults})
    if request.method=="GET" and  cid and not type:
        # print(1)
        consult=Consult.objects.filter(c_id=cid).first()
        userinfo=Userinfo.objects.filter(uid=consult.u_id).first()
        return render(request,"treat_patient.html",{'consult':consult,'userinfo':userinfo})
    if request.method=="GET" and  cid and  type=="show":
        c=Consult.objects.filter(c_id=cid).first()
        return render(request,"consult_detail.html",{'c':c})
        # return render(request,"treat_patient.html",{'consult':consult,'userinfo':userinfo})
    if request.method=="POST":
        cid=request.POST.get('cid')
        consult=Consult.objects.filter(c_id=cid).first()
        diagnosisResult=request.POST.get('diagnosisResult')#诊断结果
        RP=request.POST.get('RP')#RP
        rp=Recipe()
        rp.Rp=RP
        rp.diagnose=diagnosisResult
        rp.symptom=''
        rp.save()
        consult.r_id=rp
        consult.status=1
        consult.save()
        return redirect("/doctor/online_consult/")

def register(request):#挂号/预约管理
    rid=request.GET.get('rid')
    if request.method=="GET" and not rid:
        registers=Register.objects.filter(d_id=request.session.get("uid"))
        return render(request,"register_manage.html",{'registers':registers})
    else:
        status=request.GET.get('status')
        register=Register.objects.filter(r_id=rid).first()
        register.status=status
        register.save()

        return redirect('/doctor/register/')


from DoctorApp.QA.qa1 import KBQA2
from DoctorApp.QA.jian import PrescriptionSaver

current_question_index = 0
current_question_index1 = 0
is_prescription_query = False
additional_prescription_query = False
new_prescription_step = None
new_prescription = {'方名': '', '主治': '', '组成': '', '方剂类型': '', '用法': ''}
user_answers = []

# Function to reset state
def reset_state():
    global current_question_index, is_prescription_query, user_answers, current_question_index1, additional_prescription_query, new_prescription_step, new_prescription
    current_question_index = 0
    current_question_index1 = 0
    is_prescription_query = False
    additional_prescription_query = False
    new_prescription_step = None
    new_prescription = {'方名': '', '主治': '', '组成': '', '方剂类型': '', '用法': ''}
    user_answers = []

# Class to save prescription to database
class PrescriptionSaver:
    def __init__(self, uri, user, password):
        self.graph = Graph(uri, auth=(user, password))

    def save_prescription(self, prescription):
        try:
            prescription_type = prescription["方剂类型"]
            prescription_name = prescription["方名"]
            composition = prescription["组成"]
            indications = prescription["主治"]
            usage = prescription["用法"]

            prescription_type_node = self.graph.nodes.match("方剂类型", name=prescription_type).first()
            if not prescription_type_node:
                prescription_type_node = Node("方剂类型", name=prescription_type)
                self.graph.create(prescription_type_node)

            prescription_node = self.graph.nodes.match("方名", name=prescription_name).first()
            if not prescription_node:
                prescription_node = Node('方名', name=prescription_name, 方剂类型=prescription_type)
                self.graph.create(prescription_node)

            composition_node = self.graph.nodes.match("组成", name=composition).first()
            if not composition_node:
                composition_node = Node("组成", name=composition)
                self.graph.create(composition_node)

            indications_node = self.graph.nodes.match("主治", name=indications).first()
            if not indications_node:
                indications_node = Node("主治", name=indications)
                self.graph.create(indications_node)

            usage_node = self.graph.nodes.match("用法", name=usage).first()
            if not usage_node:
                usage_node = Node("用法", name=usage)
                self.graph.create(usage_node)

            rel = Relationship(prescription_type_node, "包含", prescription_node)
            self.graph.create(rel)
            rel = Relationship(prescription_node, "组成部分", composition_node)
            self.graph.create(rel)
            rel = Relationship(prescription_node, "主治", indications_node)
            self.graph.create(rel)
            rel = Relationship(prescription_node, "用法", usage_node)
            self.graph.create(rel)

            print(f"Prescription {prescription_name} saved successfully.")
        except Exception as e:
            print(f"Error saving prescription: {e}")

def add_prescription(request):
    # 从会话数据中获取药方列表（示例数据，这里应该从实际数据源获取）
    prescriptions = [
        {
            "药方": "六味汤",
            "方剂类型": "解表剂",
            "组成": "附子（炮）2两，细辛2两，甘草（炙）2两，人参2两，干姜3两，大黄5两。",
            "用法": "【用法用量】 上切。以水7升，煮取2升合，去滓，分温3服。服如人行10里久。1服此汤，当得快利，利中有恶物如鱼脑状，或如桃李，但异于常利，勿怪之。将息经3-4日，宜合高良姜等10味散服之。",
            "主治": "风寒喉痹，咽喉淡红不肿，吞咽不顺，恶寒发热，鼻流清涕",
            "匹配病症": "发热, 喉痹, 咽喉淡红不肿, 鼻流"
        },
        {
            "药方": "三拗汤",
            "方剂类型": "解表剂",
            "组成": "麻黄 杏仁 甘草",
            "用法": "nan",
            "主治": "感冒风邪，鼻塞声重，咳嗽痰多，胸闷气短",
            "匹配病症": "感冒, 痰, 咳嗽"
        },
        # 添加其他药方...
    ]

    prescriptions_json = json.dumps(prescriptions)
    return render(request, "add_prescription.html", {"prescriptions": prescriptions, "prescriptions_json": prescriptions_json})

@csrf_exempt
def save_prescription(request):
    if request.method == "POST":
        name = request.POST.get("name")
        prescription_type = request.POST.get("type")
        composition = request.POST.get("composition")
        usage = request.POST.get("usage")
        indications = request.POST.get("indications")

        # 保存新药方的逻辑
        new_prescription = {
            "方名": name,
            "方剂类型": prescription_type,
            "组成": composition,
            "用法": usage,
            "主治": indications
        }
        saver = PrescriptionSaver("bolt://localhost:7687", "neo4j", "12345678")
        saver.save_prescription(new_prescription)

        return redirect("DoctorApp:answer1")  # 保存成功后重定向回主页面

    return render(request, "add_prescription.html")

def answer1(request):
    global current_question_index, is_prescription_query, user_answers, current_question_index1, additional_prescription_query, new_prescription_step, new_prescription

    first_series_questions = [
        "请问您有什么不适的症状？",
        "还有什么症状？",
        "还有呢?"
    ]

    second_series_questions = [
        "发烧吗？",
        "是否有喉咙痛的症状？",
        "有痰吗？",
        "嗓子红吗？",
        "流鼻涕吗？",
        "咳嗽吗？"
    ]

    if request.method == "POST":

IM_Sys/DoctorApp/templates/answer1.html
{% extends "doctor_base.html" %}
{% block title %}
辅助诊断
{% endblock %}

{% block subtitle %}
辅助诊断
{% endblock %}

{% block main %}辅助诊断{% endblock %}

{% block header %}
<style>
    .msgshow {
        height: 450px;
        border-bottom: 1px solid rgb(136, 133, 133);
        padding: 20px;
        box-sizing: border-box;
        display: flex;
        flex-direction: column;
        overflow: auto;
    }
    .input-box {
        height: 150px;
        padding: 20px;
        box-sizing: border-box;
    }
    .answer {
        align-self: flex-start;
        border-radius: 5px;
        background-color: rgb(221, 235, 219);
        padding: 8px;
    }
    .user {
        border-radius: 5px;
        background-color: rgb(97, 230, 80);
        padding: 8px;
        align-self: flex-end;
    }
    .but {
        height: 65px;
        display: flex;
        justify-content: space-between;
        padding: 0px 20px;
        align-items: center;
    }
    button {
        border: none;
        background-color: rgb(25, 225, 65);
        width: 70px;
        height: 30px;
        border-radius: 6px;
    }
    .add-prescription-button, .ask-medicine-button {
        background-color: rgb(25, 225, 65);
        color: white;
        border: none;
        width: 90px;
        height: 30px;
        border-radius: 6px;
        cursor: pointer;
    }
</style>
<script>
    function sendmsg() {
        var msg = $(".input-box").text().trim();
        if (!msg) return;  // 如果输入框为空，则不发送
        var msg_dom = $('<p class="user">' + msg + '</p>');
        $(".msgshow").append(msg_dom);
        $('.input-box').text('');
        var csrf = $('input[name="csrfmiddlewaretoken"]').val();
        $.ajax({
            url: "{% url 'UserApp:answer' %}",
            type: "post",
            data: { "msg": msg, 'csrfmiddlewaretoken': csrf },
            dataType: "json",
        }).done(function(data) {
            var answer_dom = $('<p class="answer">' + data.answer + '</p>');
            $(".msgshow").append(answer_dom);
            // 检查是否有 additional_question 并显示
            if (data.additional_question) {
                var additional_question_dom = $('<p class="answer">' + data.additional_question + '</p>');
                $(".msgshow").append(additional_question_dom);
            }
            // 滚动到底部
            $(".msgshow").scrollTop($(".msgshow")[0].scrollHeight);
        }).fail(function() {
            alert("消息发送失败，请重试。");
        });
    }
</script>
{% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">辅助诊断</h5>

                    <!-- 消息框 -->
                    {% csrf_token %}
                    <div class="msgshow">
                        <p class="answer">欢迎使用本系统，问诊请输入1，查询药方与特定病情治疗药物请输入2</p>
                    </div>
                </div>
                <!-- 输入框 -->
                <div class="input-box" contenteditable></div>
                <div class="but">
                    <button onclick="sendmsg()">发送</button>
                    <button class="add-prescription-button" onclick="location.href='{% url 'UserApp:add_prescription' %}'">增加新药方</button>
                    <button class="ask-medicine-button" onclick="location.href='{% url 'DoctorApp:answer2' %}'">智能问药</button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

IM_Sys/DoctorApp/templates/doctor_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title style="font-size: 14px;">中医临床智能辅助诊疗系统|{% block title %} {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/img/favicon.png" rel="icon">
  <link href="/static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/static/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="/static/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="/static/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="/static/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/css/style.css" rel="stylesheet">

  <script src="/static/js/jquery.js"></script>
  <!-- jquery -->
  {% block header %}
  {% endblock %}
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="#" class="logo d-flex align-items-center">
        <img src="/static/img/logo.png" alt="">
        <span class="d-none d-lg-block" style="font-size: 14px;">中医临床智能辅助诊疗系统</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div>

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">


        
        

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{request.session.profile}}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{request.session.username}}</span>
            <!-- 显示在线用户 -->
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{request.session.username}}</h6>
              <span>{{request.session.uid}}</span>
              <!-- 角色 -->
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>


            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>退出登录</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
      <!-- ex -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>个人中心</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'DoctorApp:doctor_index' %}">
              <i class="bi bi-circle"></i><span>个人基本信息</span>
            </a>
          </li>

          <li>
            <a href="{% url 'DoctorApp:change_pwd' %}">
              <i class="bi bi-circle"></i><span>修改密码
              </span>
            </a>
          </li>
        </ul>



      <li class="nav-item">
        <a class="nav-link collapsed " href="{% url 'DoctorApp:register' %}">
          <i class="bi bi-journal-text"></i>
          <span>预约管理</span>
        </a>


      <li class="nav-item">
        <a class="nav-link collapsed " href="{% url 'DoctorApp:online_consult'%}">
          <i class="bi bi-grid"></i>
          <span>线上咨询管理</span>
        </a>
      </li><!-- End Dashboard Nav -->


     <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'DoctorApp:answer1' %}" id="answer1">
            <i class="bi bi-envelope"></i>
            <span>辅助诊断</span>
        </a>
     </li>
      <!--          -->
    </ul>
    </li><!-- End Icons Nav -->

    </ul>

    <!--    </ul>-->

  </aside><!-- End Sidebar-->

  <main id="main" class="main">
    {% csrf_token %}
    <div class="pagetitle">
      <h1>{% block main %}{% endblock %}</h1>


    </div><!-- End Page Title -->
    {% block content %}

    {% endblock %}




  </main><!-- End #main -->



  

  <!-- Vendor JS Files -->
  <script src="/static/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/vendor/chart.js/chart.min.js"></script>
  <script src="/static/vendor/echarts/echarts.min.js"></script>
  <script src="/static/vendor/quill/quill.min.js"></script>
  <script src="/static/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="/static/vendor/tinymce/tinymce.min.js"></script>
  <script src="/static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/js/main.js"></script>

</body>

</html>

IM_Sys/DoctorApp/templates/online_manage.html
{% extends "doctor_base.html" %}
{% block title %}
线上咨询管理
{% endblock %}
{% block subtitle %}
线上咨询管理
{% endblock %}


{% block main %}线上咨询管理{% endblock %}

{% block content %}






<!--表格健康档案-->
<section class="section profile">
  <div class="row">

    <section class="section">
      <div class="row">
        <div class="col-xl-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">咨询记录</h5>

              <div class="table-responsive">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>咨询编号</th>
                      <th>姓名</th>
                      <th>性别</th>
                      <th>年龄</th>
                      <th>电话号</th>
                      
                      <th>处方号</th>
                      
                      <th>状态</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in consults %}
                    <tr>

                      <td>{{forloop.counter}}</td>
                      <td>{{i.u_id.user_name}}</td>
                      <td>{{i.u_id.user_sex}}</td>
                      <td>{{i.u_id.user_age}}</td>
                      <td>{{i.u_id.phone}}</td>
                      {% if i.r_id.recipe_id %}
                      <td><a href="{% url 'DoctorApp:online_consult'%}?cid={{i.c_id}}&type=show">{{i.r_id.recipe_id}}</a></td>

                      {% else %}
                      <td>还未处理，没有处方号</td>

                      {% endif %}
                      <td>
                        <div class="btn-group">
                          {% if i.status == 0 %}
                          <a type="button" href="{% url 'DoctorApp:online_consult'%}?cid={{i.c_id}}" class="btn btn-danger btn-sm"><i
                              class="bi bi-exclamation-octagon"></i>未完成,去处理</a>

                          {% endif %}
                          {% if i.status == 1 %}

                          <span type="button"  class="btn btn-success btn-sm"><i
                              class="bi bi-check-circle"></i>已完成</span>

                          {% endif %}


                        </div>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>

            </div>
          </div>
        </div>
      </div>
  </div>

</section>

{% endblock %}