IM_Sys/IM_Sys/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from IM_Sys.views import home,login,register,test,logout,error

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home,name="home"),#首页
    path("login/",login,name="login"),#登录
    path("register/",register,name="register"),#注册
    path("logout/",logout,name="logout"),
    path("user/",include("UserApp.urls")),#用户
    path("doctor/",include("DoctorApp.urls")),#医生
    path("admin_sys/",include("adminApp.urls")),#管理员
    path("blog/",include("BlogApp.urls")),#博客
    path("error/",error,name="error"),
    path("test/",test,name="test"),
]

IM_Sys/UserApp/urls.py
from django.urls import path
from . import views

app_name = 'UserApp'

urlpatterns = [
    path("index/",views.personal_info,name="home"),#用户首页
    # path("home/",views.home,name="home"),#用户首页
    path("user_basic/",views.user_basic,name="user_basic"),#个人基本信息
    path("personal_manage/",views.personal_manage,name='personal_manage'),#个人健康档案管理
    path("personal_add/",views.personal_add,name="personal_add"),#个人健康档案添加
    path("family_manage/",views.family_manage,name='family_manage'),#家庭健康档案管理
    path("family_add/",views.family_add,name="family_add"),#家庭健康档案添加
    path("change_pwd/",views.change_pwd,name="change_pwd"),#修改密码
    path("blog/",views.blog,name="blog"),#论坛增删查改
    path("like_post/",views.like_post,name="like_post"),#点赞帖子
    path("blog_details/",views.blog_details,name="blog_details"),#论坛详情
    path("comment/",views.comment,name="comment"),#评论
    path("news/",views.news,name="news"),#新闻
    path("news_details/",views.news_details,name="news_details"),#新闻详情
    path("user_register/",views.user_register,name="user_register"),#我的预约
    path("register_online/",views.register_online,name="register_online"),#线上挂号
    path("online_consult/",views.online_consult,name="online_consult"),#线上咨询
    path("my_online_consult/",views.my_online_consult,name="my_online_consult"),#我的线上咨询
    path("answer/",views.answer,name="answer"),
    path('add_prescription/', views.add_prescription, name='add_prescription'),
    path('save_prescription/', views.save_prescription, name='save_prescription'),
path('get_doctors_by_department/<int:department_id>/', views.get_doctors_by_department, name='get_doctors_by_department'),
]

IM_Sys/UserApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator

from UserApp.models import User, Health_doc, Relative, Userinfo, PEinfo, Visit, CrawledContent
from django.http import HttpResponseRedirect
from DoctorApp.models import Doctor, Register, Department, Consult
from BlogApp.models import News, Post, Comment
import json
from django.views.decorators.csrf import csrf_exempt
from py2neo import Graph, Node, Relationship
def login_role_auth(fn):
    def wrapper(request, *args, **kwargs):
        if request.session.get('is_login', False) and request.session.get('user_type') == "/user":
            return fn(request, *args, *kwargs)
        else:
            # 获取用户当前访问的url，并传递给/user/login/
            next = request.get_full_path()
            request.session["is_login"] = False
            red = HttpResponseRedirect("/login/?" + next)
            return red

    return wrapper


# Create your views here.
@login_role_auth
def change_pwd(request):  # 个人中心 修改密码
    massage = {"info": ''}
    if request.method == "POST":
        old_pwd = request.POST.get("old_pwd")
        new_pwd = request.POST.get("new_pwd")
        if old_pwd == new_pwd:
            massage = {"info": '新密码和原密码一致', "res": 0}
        else:
            user = User.objects.filter(uid=request.session.get('uid')).first()
            if user.password != old_pwd:
                massage = {"info": '原密码不正确', "res": 1}
            else:
                user.password = new_pwd
                user.save()
                massage = {"info": '密码修改成功', "res": 2}

    return JsonResponse(massage)


@login_role_auth
def personal_info(request):  # 个人中心 个人信息
    user = User.objects.filter(uid=request.session.get('uid')).first()
    infos = Userinfo.objects.filter(uid=user).order_by('-c_time')
    nui = infos.first()  # 最新个人信息

    return render(request, "user_index.html", {"user": user, 'nui': nui})


@login_role_auth
def user_basic(request):  # 个人中心 个人基本信息

    user = User.objects.filter(uid=request.session.get('uid')).first()
    return render(request, "user_basic.html", {"user": user})


@login_role_auth
def health_archives(request):  # 档案管理
    if request.method == "GET":
        health_doc = Health_doc.objects.filter(uid=request.session.get("uid"))
        return render(request, ".html", {"health_doc": health_doc})
    if request.method == "POST":
        pass


def personal_add(request):  # 个人档案添加
    user = User.objects.filter(uid=request.session.get('uid')).first()
    departments = Department.objects.all()  # 查询所有科室
    if request.method == "POST":
        type = request.POST.get("type")
        id = request.POST.get("id")
        if type == "info":
            ui = Userinfo.objects.filter(infoid=id).first() if id else Userinfo()
            # ui=Userinfo()

            ui.uid = user
            user_name = request.POST.get("user_name")
            user.user_name = user_name
            ui.user_name = user_name
            user_sex = request.POST.get("user_sex")
            user.user_sex = user_sex
            ui.user_sex = user_sex
            user_age = request.POST.get("user_age")
            user.user_age = user_age
            ui.user_age = user_age
            user_height = request.POST.get("user_height")
            ui.user_height = user_height
            user_weight = request.POST.get("user_weight")
            ui.user_weight = user_weight
            allergy = request.POST.get("allergy")
            ui.allergy = allergy

            illness = request.POST.get("illness")
            ui.illness = illness
            disability = request.POST.get("disability")
            ui.disability = disability

            common_drugs = request.POST.get("common_drugs")
            ui.common_drugs = common_drugs
            if not id:
                user.save()
            ui.save()

            return redirect("/user/personal_manage/")
        elif type == "PE":
            # p=PEinfo()
            p = PEinfo.objects.filter(PEid=id).first() if id else PEinfo()

            p.uid = user

            # user_name=request.POST.get("user_name")
            p.user_name = user.user_name

            # user_sex=request.POST.get("user_sex")
            p.user_sex = user.user_sex

            hospital = request.POST.get("hospital")
            p.hospital = hospital

            items = request.POST.get("items", '')
            p.items = items

            blood_sugar = request.POST.get("blood_sugar")
            p.blood_sugar = blood_sugar

            total_cholesterol = request.POST.get("total_cholesterol")
            p.total_cholesterol = total_cholesterol

            triglyceride = request.POST.get("triglyceride")
            p.triglyceride = triglyceride

            minimum = request.POST.get("minimum")
            p.minimum = minimum

            maximum = request.POST.get("maximum")
            p.maximum = maximum

            heart_rate = request.POST.get("heart_rate")
            p.heart_rate = heart_rate
            date = request.POST.get("date")
            p.date = date

            p.save()

            return redirect("/user/personal_manage/")

        elif type == "visit":
            # v=Visit()
            v = Visit.objects.filter(vid=id).first() if id else Visit()
            departments = Department.objects.all()  # 查询所有科室

            v.uid = user

            # user_name=request.POST.get("user_name")
            v.user_name = user.user_name

            # user_sex=user.request.POST.get("user_sex")
            v.user_sex = user.user_sex

            department = request.POST.get("department")
            v.department = department

            chief_complaint = request.POST.get("chief_complaint")
            v.chief_complaint = chief_complaint

            HPI = request.POST.get("HPI")
            v.HPI = HPI

            PH = request.POST.get("PH")
            v.PH = PH

            diagnose = request.POST.get("diagnose")
            v.diagnose = diagnose

            prescription = request.POST.get("prescription")
            v.prescription = prescription

            DA = request.POST.get("DA")
            v.DA = DA

            date = request.POST.get("date")
            v.date = date

            v.save()

            return redirect("/user/personal_manage/")

    return render(request, "personal_add.html",
                  {"user": user, 'active_menu': 'personal_add', 'departments': departments})


@login_role_auth
def personal_manage(request):  # 个人健康档案管理
    user = User.objects.filter(uid=request.session.get('uid')).first()
    if request.method == "GET":
        t = request.GET.get("type")
        i = request.GET.get("id")
        change = request.GET.get("change")
        if t and not change:
            if t == "info":
                info = Userinfo.objects.filter(infoid=i).first()
                info.delete()
            if t == "visit":
                v = Visit.objects.filter(vid=i).first()
                v.delete()
            if t == "PE":
                p = PEinfo.objects.filter(PEid=i).first()
                p.delete()
            return redirect("/user/personal_manage/")
        elif t and change:
            if t == "info":
                info = Userinfo.objects.filter(infoid=i).first()
                return render(request, "change_info.html", {"info": info, 'active_menu': 'personal_manage'})
            if t == "visit":
                v = Visit.objects.filter(vid=i).first()
                return render(request, "change_visit.html", {"v": v, 'active_menu': 'personal_manage'})
            if t == "PE":
                p = PEinfo.objects.filter(PEid=i).first()
                return render(request, "change_PE.html", {"p": p, 'active_menu': 'personal_manage'})
            pass

        infos = Userinfo.objects.filter(uid=user).order_by('-c_time')
        nui = infos.first()  # 最新个人信息
        PEs = PEinfo.objects.filter(uid=user).order_by('-c_time')  # 体检信息
        vs = Visit.objects.filter(uid=user).order_by('-c_time')  # 就诊记录

        return render(request, "personal_manage.html", {"user": user, "nui": nui, "infos": infos, 'PEs': PEs, "vs": vs,
                                                        'active_menu': 'personal_manage'})
    elif request.method == "POST":
        iid = request.POST.get("iid")
        if iid:
            ui = Userinfo.objects.filter(infoid=iid).first()
        else:
            ui = Userinfo()
        ui.uid = user
        user_name = request.POST.get("user_name")
        user.user_name = user_name
        ui.user_name = user_name
        user_sex = request.POST.get("user_sex")
        user.user_sex = user_sex
        ui.user_sex = user_sex
        user_age = request.POST.get("user_age")
        user.user_age = user_age
        ui.user_age = user_age
        user_height = request.POST.get("user_height")
        ui.user_height = user_height
        user_weight = request.POST.get("user_weight")
        ui.user_weight = user_weight
        allergy = request.POST.get("allergy")
        ui.allergy = allergy

        illness = request.POST.get("illness")
        ui.illness = illness
        disability = request.POST.get("disability")
        ui.disability = disability
        id_no = request.POST.get("id_no")
        phone = request.POST.get("phone")
        user.id_no = id_no
        user.phone = phone

        common_drugs = request.POST.get("common_drugs")
        ui.common_drugs = common_drugs

        ui.save()
        user.save()
        return redirect("/user/personal_manage/")


@login_role_auth
def family_add(request):  # 家庭健康档案添加
    if request.method == "POST":
        user = User.objects.filter(uid=request.session.get('uid')).first()
        relative = Relative()
        relative.uid = user
        relative.relationship = request.POST.get('relationship')
        relative.relative_name = request.POST.get('relative_name')
        relative.relative_sex = request.POST.get('relative_sex')

IM_Sys/UserApp/templates/add_prescription.html
{% extends "answer.html" %}
{% block title %}
增加新药方
{% endblock %}

{% block subtitle %}
增加新药方
{% endblock %}

{% block main %}增加新药方{% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">增加新药方</h5>
                    <form id="add-prescription-form" method="post" action="{% url 'UserApp:save_prescription' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="prescription-select" class="form-label">选择药方</label>
                            <select id="prescription-select" class="form-control">
                                <option value="">请选择</option>
                                {% for prescription in prescriptions %}
                                    <option value="{{ prescription.药方 }}">{{ prescription.药方 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="name" class="form-label">药方名</label>
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                        <div class="mb-3">
                            <label for="type" class="form-label">方剂类型</label>
                            <input type="text" class="form-control" id="type" name="type" required>
                        </div>
                        <div class="mb-3">
                            <label for="composition" class="form-label">组成</label>
                            <input type="text" class="form-control" id="composition" name="composition" required>
                        </div>
                        <div class="mb-3">
                            <label for="usage" class="form-label">用法</label>
                            <input type="text" class="form-control" id="usage" name="usage" required>
                        </div>
                        <div class="mb-3">
                            <label for="indications" class="form-label">主治</label>
                            <input type="text" class="form-control" id="indications" name="indications" required>
                        </div>
                        <button type="submit" class="btn btn-primary">保存</button>
                        <button type="button" class="btn btn-secondary" onclick="window.history.back()">返回</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    const prescriptions = {{ prescriptions_json|safe }};

    document.getElementById('prescription-select').addEventListener('change', function() {
        const selectedPrescription = prescriptions.find(prescription => prescription.药方 === this.value);
        if (selectedPrescription) {
            document.getElementById('name').value = selectedPrescription.药方;
            document.getElementById('type').value = selectedPrescription.方剂类型;
            document.getElementById('composition').value = selectedPrescription.组成;
            document.getElementById('usage').value = selectedPrescription.用法;
            document.getElementById('indications').value = selectedPrescription.主治;
        } else {
            document.getElementById('name').value = '';
            document.getElementById('type').value = '';
            document.getElementById('composition').value = '';
            document.getElementById('usage').value = '';
            document.getElementById('indications').value = '';
        }
    });
</script>
{% endblock %}

IM_Sys/UserApp/templates/change_info.html
{% extends "user_base.html" %}
{% block title %}
个人基本信息修改
{% endblock %}

{% block subtitle %}
个人基本信息修改
{% endblock %}


{% block main %}个人基本信息修改{% endblock %}

{% block content %}

<div class="card">
  <div class="card-body">
    <h5 class="card-title">个人基本信息修改</h5>

    <!-- Default Tabs -->
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button"
          role="tab" aria-controls="home" aria-selected="true">基本信息</button>
      </li>
    </ul>

    <!-- 个人基本信息 -->
    <div class="tab-content pt-2" id="myTabContent" >
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <!-- Vertical Form -->
        <form class="row g-3" method="post" action="{% url 'UserApp:personal_add'%}">
          {% csrf_token %}
          <div class="col-md-12">
            <label for="user_name" class="form-label">姓名</label>
            <input type="text" class="form-control" id="user_name" name="user_name"  value="{{info.user_name}}">
          </div>
          <input type="hidden" value="info" name="type">
          <input type="hidden" name="id" value="{{info.infoid}}">

          <div class="col-md-12">
            <label for="user_age" class="form-label">年龄</label>
            <input type="text" class="form-control" id="user_age" name="user_age"  value="{{info.user_age}}">
          </div>

          <div class="col-md-12">
            <label for="inputState" class="form-label">性别</label>
            <select id="user_sex" class="form-select" name="user_sex"  >
              {% if info.user_sex  == '男' %}
              <option selected>男</option>
              <option>女</option>
              {% else %}
              <option >男</option>
              <option selected>女</option>
              {% endif %}
            </select>
          </div>

          <div class="col-md-12">
            <label for="user_height" class="form-label">身高(cm)</label>
            <input type="text" class="form-control" id="user_height" value="{{info.user_height}}" placeholder="如165" name="user_height">
          </div>
          <div class="col-md-12">
            <label for="user_weight" class="form-label">体重(kg)</label>
            <input type="text" class="form-control" id="user_weight" value="{{info.user_weight}}" placeholder="如55" name="user_weight">
          </div>

          <div class="col-12">
            <label for="allergy" class="form-label">药物过敏史</label>
            <!-- <input type="text"  id="modelCode" class="typeahead form-control" data-provide="typeahead"> -->
            <input type="text" class="form-control" id="allergy" value="{{info.allergy}}" placeholder="如青霉素、磺胺、链霉素等" name="allergy">
          </div>

          <div class="col-md-12">
            <label for="illness" class="form-label">疾病史</label>
            <input type="text" class="form-control" id="illness" value="{{info.illness}}" placeholder="如高血压、糖尿病、冠心病、慢性阻塞性肺疾病等" name="illness">
          </div>
          <div class="col-md-12">
            <label for="disability" class="form-label">残疾</label>
            <input type="text" class="form-control" id="disability" value="{{info.disability}}" placeholder="如视力残疾、听力残疾、言语残疾、肢体残疾等" name="disability">
          </div>

          <div class="col-md-12">
            <label for="common_drugs" class="form-label">常用药</label>
            <input type="text" class="form-control" id="common_drugs" value="{{info.common_drugs}}" name="common_drugs" placeholder="有请输入手术名称，没有输入无">
          </div>



          <div class="text-center">
            <button type="submit" class="btn btn-primary">提交</button>
            <button type="reset" class="btn btn-secondary">重置</button>
          </div>
        </form><!-- Vertical Form -->
      </div>


  </div>
</div>


{% endblock %}

IM_Sys/UserApp/templates/choose_doctor.html
{% extends "user_base.html" %}
{% block title %}
线上咨询
{% endblock %}

{% block subtitle %}
线上咨询 <li class="breadcrumb-item">选择医生</li>
{% endblock %}


{% block main %}线上咨询{% endblock %}

{% block content %}





<section class="section">
  <div class="row">
    <div class="col-lg-12">

      <!-- Default Card -->
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">科室介绍</h5>

          <div class="row mb-3">
            <label class="col-sm-4 col-form-label">选择科室</label>

            <div class="col-sm-6">
              <select class="form-select" aria-label="Default select example" id="department">
                <option selected></option>
                {% for d in departments %}

                <option value={{d.id}}>{{d.d_name}}</option>

                {% endfor %}
              </select>
            </div>
          </div>

          <div id="dintroduce">
            {{de.introduce}}
          </div>
        </div><!-- End Default Card -->
        <script>
          $("#department").on("change", function () {
            location.href = "http://127.0.0.1:8000/user/online_consult/?deid=" + $("#department").val()
          })
          $(function () {
            $("#department").val({{ de.id }})
            })

        </script>


      </div>
      <!-- End Card with header and footer -->
      <div class="row">
        {% for d in doctors %}
        <div class="col-lg-3 col-md-3">

          <!-- Card with an image on top -->
          <div class="card">
            <img src="{{d.profile}}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{d.doctor_name}}</h5>
              <p class="card-text">{{d.good_at}}</p>
              <a href="{% url 'UserApp:online_consult'%}?did={{d.uid}}" class="btn btn-primary">咨询</a>

            </div><!-- End Card with an image on top -->
          </div>
        </div>
        {% endfor %}
      </div>

    </div>
</section>








{% endblock %}

IM_Sys/UserApp/templates/register_online.html
{% extends "user_base.html" %}
{% block title %}
线上挂号
{% endblock %}

{% block subtitle %}
线上挂号
{% endblock %}

{% block main %}线上挂号{% endblock %}

{% block content %}
<!-- 挂号 -->

<div class="col-lg-10">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">挂号信息填写</h5>

      <!-- General Form Elements -->
      <form method="post" action="{% url 'UserApp:register_online' %}">
        {% csrf_token %}
        <input type="hidden" class="form-control" value="{{ user.uid }}" name="uid">

        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">姓名</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{ user.user_name }}" disabled>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">性别</label>
          <div class="col-sm-10">
            <select class="form-select" aria-label="Default select example" disabled>
              {% if user.user_sex == "1" %}
              <option selected value="1">男</option>
              <option value="2">女</option>
              {% else %}
              <option value="1">男</option>
              <option selected value="2">女</option>
              {% endif %}
            </select>
          </div>
        </div>

        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">年龄</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{ user.user_age }}" disabled>
          </div>
        </div>

        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">电话号码</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{ user.phone }}" disabled>
          </div>
        </div>

        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">身份证号</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{ user.id_no }}" disabled>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">科室</label>
          <div class="col-sm-10">
            <select class="form-select" aria-label="Default select example" id="department">
              <option selected=""></option>
              {% for d in departments %}
              <option value="{{ d.id }}">{{ d.d_name }}</option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">挂号类型</label>
          <div class="col-sm-10">
            <select class="form-select" aria-label="Default select example" name="r_type">
              <option selected=""></option>
              <option value="急诊">急诊</option>
              <option value="普通门诊">普通门诊</option>
            </select>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">医生</label>
          <div class="col-sm-10">
            <select class="form-select" aria-label="Default select example" id="c_doctor" name="d_id">
            </select>
          </div>
        </div>

        <div class="row mb-3">
          <label for="inputDate" class="col-sm-2 col-form-label">挂号日期</label>
          <div class="col-sm-10">
            <input type="date" class="form-control" name="date">
          </div>
        </div>

        <div class="row mb-3">
          <label for="inputTime" class="col-sm-2 col-form-label">时间段</label>
          <div class="col-sm-10">
            <select name="s_time" id="s_time">
              {% for i in time_range %}
              <option value="{{ i }}">{{ i }}</option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="row mb-3">
          <label class="col-sm-2 col-form-label"></label>
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">提交</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
  </div>
</div>
<!-- 挂号结束 -->

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function () {
    $("#department").on("change", function () {
      var departmentId = $(this).val();
      if (departmentId) {
        $.ajax({
          url: "{% url 'UserApp:get_doctors_by_department' 0 %}".replace('0', departmentId),
          type: "GET",
          success: function (data) {
            var doctorOptions = '<option value="">请选择医生</option>';
            for (var i = 0; i < data.length; i++) {
              doctorOptions += '<option value="' + data[i].uid + '">' + data[i].doctor_name + '</option>';
            }
            $("#c_doctor").html(doctorOptions);
          }
        });
      } else {
        $("#c_doctor").html('<option value="">请选择医生</option>');
      }
    });
  });
</script>
{% endblock %}

IM_Sys/UserApp/templates/user_register.html
{% extends "user_base.html" %}
{% block title %}
我的预约
{% endblock %}

{% block subtitle %}
我的预约
{% endblock %}


{% block main %}
    我的预约
{% endblock %}

{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-lg-10">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">预约记录</h5>

                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>编号</th>
                                        <th>姓名</th>
                                        <th>科室</th>
                                        <th>挂号类型</th>
                                        <th>医生</th>
                                        <th>挂号日期</th>
                                        <th>挂号时间段</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for mr in my_re %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{mr.u_id.user_name}}</td>
                                        <td>{{mr.d_id.deid.d_name}}</td>
                                        <td>{{mr.r_type}}</td>
                                        <td>{{mr.d_id.doctor_name}}</td>
                                        <td>{{mr.date|date:"Y-m-d"}}</td>
                                        <td>{{mr.s_time}}--{{mr.end_time}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-outline-danger btn-sm">
                                                    <a href="{% url 'UserApp:user_register' %}?rid={{mr.r_id}}"
                                                        style="color:#dc3545;">删除</a>
                                                </button>
                                                <span>|</span>
                                                <button type="button" class="btn btn-outline-info btn-sm">
                                                    <a href="{% url 'UserApp:register_online' %}?rid={{mr.r_id}}"
                                                        style="color:#dc3545;">修改</a>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>
        $(document).ready(function () {
            // Listen for department change event
            $('#department').change(function () {
                var departmentId = $(this).val();
                // Send AJAX request to get doctors for selected department
                $.ajax({
                    url: '/get_doctors/', // Replace with your backend endpoint
                    method: 'GET',
                    data: { departmentId: departmentId },
                    success: function (data) {
                        // Clear existing doctor options
                        $('#doctor').empty();
                        // Populate doctor options based on response data
                        data.forEach(function (doctor) {
                            $('#doctor').append($('<option>', {
                                value: doctor.id,
                                text: doctor.name
                            }));
                        });
                    },
                    error: function (xhr, status, error) {
                        console.error(error);
                    }
                });
            });
        });
    </script>
{% endblock %}