IM_Sys/IM_Sys/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from IM_Sys.views import home,login,register,test,logout,error

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home,name="home"),#首页
    path("login/",login,name="login"),#登录
    path("register/",register,name="register"),#注册
    path("logout/",logout,name="logout"),
    path("user/",include("UserApp.urls")),#用户
    path("doctor/",include("DoctorApp.urls")),#医生
    path("admin_sys/",include("adminApp.urls")),#管理员
    path("blog/",include("BlogApp.urls")),#博客
    path("error/",error,name="error"),
    path("test/",test,name="test"),
]

IM_Sys/adminApp/urls.py
from django.urls import path
import IM_Sys.views
from adminApp import views
app_name = 'adminApp'

urlpatterns = [
    path("index/",views.personal_info,name="admin_index"),#管理员首页
    path("change_pwd/",views.change_pwd,name="change_pwd"),#修改密码
    path("user_manage/",views.user_manage,name="user_manage"),#用户管理
    path("user_manage1/",views.user_manage1,name="user_manage1"),#用户管理
    path("user_manage2/",views.user_manage2,name="user_manage2"),#用户管理
    path("doctor_manage/",views.doctor_manage,name="doctor_manage"),#医生管理
    path("patient_manage/",views.user_manage2,name="patient"),#医生管理
    path("health_news/",views.health_news,name="health_news"),#健康咨询管理
    path("discuss_manage/",views.blog_manage,name="discuss_manage"),#论坛管理
    path("discuss_manage/",views.blog_manage,name="discuss_manage"),#论坛管理
    path("edit_doctor_info/",views.edit_doctor_info,name="edit_doctor_info"),
    path("keshi/",views.keshi,name="keshi"),
    path("info/",views.info,name="info"),
    path('info/edit/<int:infoid>/', views.ehi, name='ehi'),
    path('keshi/add/', views.add_department, name='add_department'),
    path('keshi/delete/', views.delete_department, name='delete_department'),
    path('info/<int:PEid>/', views.ehi1, name='ehi1'),
    path('info/ed/<int:vid>/', views.ehi2, name='ehi2'),





]

IM_Sys/adminApp/models.py
import django
from django.db import models

import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "IM_Sys.IM_Sys.settings")

# Create your models here.
class Manager(models.Model):
    uid=models.AutoField(primary_key=True)#用户编号
    manager_name = models.CharField(max_length=20)#用户名
    email= models.CharField(max_length=20)#邮箱
    password= models.CharField(max_length=20)#密码
    manager_sex= models.CharField(max_length=20)#性别
    manager_age= models.IntegerField()#年龄
    role= models.CharField(max_length=20)#角色
    states=models.IntegerField(default=1)#权限
    c_time= models.DateTimeField(auto_now_add=True) #注册时间

IM_Sys/adminApp/views.py
from django.shortcuts import render,redirect
from adminApp.models import Manager
from DoctorApp.models import Doctor,Department
from BlogApp.models import News,Post,Comment
from UserApp.models import User,Visit,Userinfo,PEinfo
from django.http import HttpResponse
from django.http import HttpResponseRedirect,JsonResponse

def login_role_auth(fn):
    def wrapper(request,*args,**kwargs):
        if request.session.get('is_login', False) and request.session.get('user_type')=="/admin_sys" :
            return fn(request,*args,*kwargs)
        else:
            # 获取用户当前访问的url，并传递给/user/login/
            next = request.get_full_path() 
            request.session["is_login"]=False
            red = HttpResponseRedirect("/login/")
            return red
    return wrapper

@login_role_auth
def change_pwd(request):#个人中心 修改密码
    massage={"info":''}
    if request.method=="POST":
        old_pwd=request.POST.get("old_pwd")
        new_pwd=request.POST.get("new_pwd")
        if old_pwd==new_pwd:
            massage={"info":'新密码和原密码一致',"res":0}
        else:
            user=Manager.objects.filter(uid=request.session.get('uid')).first()
            if user.password!=old_pwd:
                massage={"info":'原密码不正确',"res":1}
            else:
                user.password=new_pwd
                user.save()
                massage={"info":'密码修改成功',"res":2}
        return JsonResponse(massage) 
    else:
        return render(request,"admin_pwd.html",massage)
def personal_info(request):#个人中心 个人信息
    if request.method=="GET":
        manager=Manager.objects.filter(uid=request.session.get('uid')).first()
        return render(request,"admin_index.html",{"user":manager})
    elif request.method=="POST":
        manager=Manager.objects.filter(uid=request.session.get('uid')).first()
        manager_name=request.POST.get('manager_name')
        email=request.POST.get('email')
        manager_sex=request.POST.get('manager_sex')
        manager_age=request.POST.get('manager_age')
        department = request.POST.get('department')
        manager.manager_name=manager_name
        manager.email=email
        manager.manager_sex=manager_sex
        manager.manager_age=manager_age
        manager.department = department
        manager.save()
        return redirect("/admin_sys/index/")

@login_role_auth
def user_manage(request):#用户管理
    user_id=request.GET.get("uid")
    if request.method=="GET" and not user_id:
        users=User.objects.all()
        return render(request,"patient_manage.html",{"users":users})
    elif user_id:
        user=User.objects.filter(uid=user_id).first()
        user.states=0
        user.save()
        return redirect("/admin_sys/user_manage/")

        return redirect("/admin_sys/user_manage/")
    if request.method=="POST":
        user_id=request.POST


def user_manage1(request):
    user_id = request.GET.get("uid")
    if request.method == "GET" and not user_id:
        users = User.objects.all()
        return render(request, "patient_manage.html", {"users": users})
    elif user_id:
        user = User.objects.filter(uid=user_id).first()
        user.states = 1
        user.save()
        return redirect("/admin_sys/user_manage/")

        return redirect("/admin_sys/user_manage/")
    if request.method == "POST":
        user_id = request.POST

@login_role_auth
def doctor_manage(request):  # 医生管理 增删查改
    uid = request.GET.get("uid")

    if request.method == "GET" and not uid:  # 查询所有医生
        doctors = Doctor.objects.all()
        return render(request, "doctor_manage.html", {"doctors": doctors})

    elif uid:  # 处理传入的uid
        type = request.GET.get("type")

        doctor = Doctor.objects.filter(uid=uid).first()
        if type in ["1", "2"]:  # 处理通过/驳回操作
            doctor.states = int(type)

            doctor.save()

        if type == "10" and request.method == "POST":  # 处理编辑操作
            doctor.doctor_name = request.POST.get("doctor_name")
            doctor.email = request.POST.get("email")
            doctor.doctor_sex = request.POST.get("doctor_sex")
            doctor.doctor_age = request.POST.get("doctor_age")
            doctor.deid = request.POST.get("deid")
            doctor.hospital = request.POST.get("hospital")
            doctor.role = request.POST.get("role")
            doctor.good_at = request.POST.get("good_at")
            doctor.save()

        return redirect("/admin_sys/doctor_manage/")

    elif request.method == "POST":
        type = request.POST.get("type")
        if type == "add":
            pass
        elif type == "change":
            pass
        elif type == "delete":
            uid = request.POST.get("uid")
            doctor = Doctor.objects.filter(uid=uid).first()
            doctor.delete()

        return redirect("/admin_sys/doctor_manage/")  # 添加这一行来确保在POST请求中有返回值

    return redirect("/admin_sys/doctor_manage/")  # 添加这一行来确保在其他情况下也有返回值




def edit_doctor_info(request):
    if request.method == 'POST':
        uid = request.GET.get('uid')
        departments = Department.objects.all()
        if not uid:
            return HttpResponse("Invalid request. UID is missing in the POST data.")

        try:
            doctor = Doctor.objects.get(uid=uid)
        except Doctor.DoesNotExist:
            return HttpResponse("Doctor matching query does not exist.")

        doctor.doctor_name = request.POST.get("doctor_name")
        doctor.email = request.POST.get("email")
        doctor.doctor_sex = request.POST.get("doctor_sex")
        doctor.doctor_age = request.POST.get("doctor_age")
        deid = request.POST.get('deid')
        doctor.deid = Department.objects.filter(id=deid).first()
        doctor.hospital = request.POST.get('hospital')
        doctor.good_at = request.POST.get('good_at')
        doctor.title = request.POST.get('title')
        doctor.save()
        return redirect('/admin_sys/doctor_manage/')  # 重定向到医生管理页面
    else:
        uid = request.GET.get('uid')
        departments = Department.objects.all()
        if not uid:
            return HttpResponse("Invalid request. UID is missing in the GET data.")

        try:
            doctor = Doctor.objects.get(uid=uid)
        except Doctor.DoesNotExist:
            return HttpResponse("Doctor matching query does not exist.")

        return render(request, 'edit_doctor_info.html', {'doctor': doctor,'departments':departments})


def user_manage2(request):#用户管理
    if request.method=="POST":
        user_id=request.GET.get("uid")
        visit = Visit.objects.all()
        if not user_id:
            return HttpResponse("Invalid request. UID is missing in the POST data.")
        try:
            user= User.objects.get(uid=user_id)

        except User.DoesNotExist:
            return HttpResponse("user matching query does not exist.")
        user.user_name = request.POST.get("user_name")
        user.password = request.POST.get("password")
        user.email = request.POST.get("email")
        user.user_sex = request.POST.get("user_sex")
        user.user_age = request.POST.get("user_age")


        user.save()
        return redirect('/admin_sys/user_manage/')  # 重定向到医生管理页面

    else:
        user_id = request.GET.get('uid')
        visit = Visit.objects.all()
        if not user_id:
            return HttpResponse("Invalid request. UID is missing in the GET data.")

        try:
            user = User.objects.get(uid=user_id)
        except User.DoesNotExist:
            return HttpResponse("User matching query does not exist.")

        return render(request, 'edit_user_info.html', {'user': user,'visit':visit})

# class Department(models.Model):#所属科室
#     id=models.AutoField(primary_key=True)
#     d_name= models.CharField(max_length=255)#科室名称
#     introduce=models.TextField(null=True)#科室介绍




def keshi(request):
    departments = Department.objects.all()

    for department in departments:
        department.doctors = Doctor.objects.filter(deid__d_name=department.d_name)

    return render(request, 'keshi_manage.html', {'departments': departments})

def add_department(request):
    if request.method == 'POST':
        d_name = request.POST.get('d_name')
        introduce = request.POST.get('introduce')
        if d_name and introduce:
            Department.objects.create(d_name=d_name, introduce=introduce)
            messages.success(request, '科室已成功添加')
        return redirect('adminApp:keshi')
    return redirect('adminApp:keshi')

def delete_department(request):
    if request.method == 'POST':
        department_id = request.POST.get('department_id')
        department = get_object_or_404(Department, id=department_id)
        department.delete()
        messages.success(request, '科室已成功删除')
        return redirect('adminApp:keshi')
    return redirect('adminApp:keshi')


def info(request):

    userinfos = Userinfo.objects.all()
    pEinfos = PEinfo.objects.all()
    visits = Visit.objects.all()


    return render(request, 'info_manage.html', {'userinfos': userinfos,'pEinfos': pEinfos,'visits': visits})

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from django.contrib import messages
def ehi(request, infoid):
    userinfo = get_object_or_404(Userinfo, infoid=infoid)

    if request.method == 'POST':
        userinfo.user_name = request.POST.get('user_name')
        userinfo.user_height = request.POST.get('user_height')
        userinfo.user_weight = request.POST.get('user_weight')
        userinfo.allergy = request.POST.get('allergy')
        userinfo.illness = request.POST.get('illness')
        userinfo.disability = request.POST.get('disability')
        userinfo.common_drugs = request.POST.get('common_drugs')

        userinfo.save()
        messages.success(request, '健康档案已成功更新')
        return redirect(reverse('adminApp:info'))

    return render(request, 'ehi.html', {'userinfo': userinfo})
def ehi1(request, PEid):
    pEinfo = get_object_or_404(PEinfo, PEid=PEid)
    if request.method == 'POST':

IM_Sys/adminApp/templates/discuss_manage.html
{% extends "admin_base.html" %}
{% block title %}
论坛管理
{% endblock %}

{% block subtitle %}
论坛管理/历史帖子
{% endblock %}


{% block main %}论坛管理{% endblock %}

{% block content %}

<!--表格健康档案-->
<section class="section profile">
  <div class="row">

    <section class="section">
      <div class="row">
        <div class="col-xl-12">

          <div class="card">
            <div class="card-body">
              <!-- <h5 class="card-title">
                <a class="btn btn-danger" href="#!"><i class="mdi mdi-window-close"></i> 批量删除</a>
              </h5> -->
              <h5></h5>

              <div class="table-responsive">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <!-- <th>
                        <label class="lyear-checkbox checkbox-primary">
                          <input type="checkbox" id="check-all"><span></span>
                        </label>
                      </th> -->
                      <th>文章编号</th>
                      <th>文章标题</th>
                      <th>点赞数</th>
                      <th>发布人</th>
                      <th>发布日期</th>

                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for post in posts %}
                    <tr>

                      <!-- <td>
                        <label class="lyear-checkbox checkbox-primary">
                          <input type="checkbox" name="ids[]" value="1"><span></span>
                        </label>
                      </td> -->
                      <td>{{post.post_id}}</td>
                      <td>{{post.post_title}}</td>
                      <td>{{post.users_like.count}}</td>
                      <td>{{post.u_id.user_name}}</td>
                      <td>{{post.c_time}}2</td>
                      <td>
                        <div class="btn-group">
                          <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:discuss_manage' %}?pid={{post.post_id}}&type=show">详情</a>
                          <span>|</span>
                          <!-- <a type="button" class="btn btn-outline-warning btn-sm" href="{% url 'adminApp:discuss_manage' %}?pid={{post.post_id}}&type=delete">查看评论</a>
                          <span>|</span> -->
                          <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'adminApp:discuss_manage' %}?pid={{post.post_id}}&type=delete">删除</a>
                        </div>
                      </td>
                    </tr>
                    {% endfor %}
                    
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>

</section>



{% endblock %}

IM_Sys/adminApp/templates/doctor_manage.html
{% extends "admin_base.html" %}
{% block title %}
医生管理
{% endblock %}

{% block subtitle %}
用户权限管理/医生管理
{% endblock %}


{% block main %}医生管理{% endblock %}

{% block content %}

<section class="section">
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <div class="card-body">
          <ul class="nav nav-tabs nav-tabs-bordered">
            <li class="nav-item">
              <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">信息</button>
            </li>
          </ul>


          <div class="tab-content pt-2">
            <div class="tab-pane fade show active profile-overview" id="profile-overview">
              <h5 class="card-title">
                <!-- <a class="btn btn-danger" href="#!"><i class="mdi mdi-window-close"></i> 批量驳回</a> -->
                <!-- <a class="btn btn-primary" href="#!"><i class="mdi mdi-window-close"></i> 批量通过</a> -->
              </h5>
              <div class="table-responsive">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <!-- <th>
                        <label class="lyear-checkbox checkbox-primary">
                          <input type="checkbox" id="check-all"><span></span>
                        </label>
                      </th> -->
                      <th>用户编号</th>
                      <!-- <th>角色</th> -->
                      <th>姓名</th>
                      <th>性别</th>
                      <th>年龄</th>
                      <th>邮箱</th>
                      <th>所属科室</th>
                      <th>所属医院</th>
                      <th>擅长领域</th>
                      <th>职称</th>
                      <th>注册日期</th>
                      <th>状态</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for doctor in doctors %}
                    <tr>
                      <!-- <td>
                        <label class="lyear-checkbox checkbox-primary">
                          <input type="checkbox" name="ids[]" value="1"><span></span>
                        </label>
                      </td> -->
                      <td>{{doctor.uid}}</td>
                      <td>{{doctor.doctor_name}}</td>
                      <td>{{doctor.doctor_sex}}</td>
                      <td>{{doctor.doctor_age}}</td>
                      <td>{{doctor.email}}</td>
                      <td>{{doctor.deid.d_name}}</td>
                      <td>{{doctor.hospital}}</td>
                      <td>{{doctor.good_at}}</td>
                      <td>{{doctor.title}}</td>
                      <td>{{doctor.c_time}}</td>
                      {% if doctor.states == 1 %}
                      <td>已通过,正常使用</td>
                      <td>
                        <div class="btn-group">
                          <div class="btn-group">
                            <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'adminApp:doctor_manage' %}?uid={{doctor.uid}}&type=2">驳回</a>
                            <span>|</span>
                            <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:doctor_manage' %}?uid={{doctor.uid}}&type=1">通过</a>
                            <span>|</span>
                               <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:edit_doctor_info' %}?uid={{doctor.uid}}">编辑</a>






                          </div>
                        </div>
                      </td>
                      {% elif doctor.states == 2 %}
                      <td>已驳回</td>
                      <td>
                        <div class="btn-group">
                          <div class="btn-group">
                            <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'adminApp:doctor_manage' %}?uid={{doctor.uid}}&type=2">驳回</a>
                            <span>|</span>
                            <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:doctor_manage' %}?uid={{doctor.uid}}&type=1">通过</a>
                            <span>|</span>
                            <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:edit_doctor_info' %}?uid={{doctor.uid}}">编辑</a>
                          </div>
                        </div>
                      </td>
                      {% else %}
                      <td>待审核</td>
                      <td>
                        <div class="btn-group">
                          <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'adminApp:doctor_manage' %}?uid={{doctor.uid}}&type=2">驳回</a>
                          <span>|</span>
                          <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:doctor_manage' %}?uid={{doctor.uid}}&type=1">通过</a>
                        </div>
                      </td>
                      {% endif %}
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>




            <div class="tab-pane fade pt-3" id="profile-change-password">
              <!-- Profile Edit Form -->
              <form action="{% url 'adminApp:doctor_manage'%}" method="post">
                {% csrf_token %}

                <div class="row mb-3">
                  <label for="doctor_name" class="col-md-4 col-lg-3 col-form-label">姓名</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="doctor_name" type="text" class="form-control" id="doctor_name" value="{{doctor.doctor_name}}">
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="doctor_sex" class="col-md-4 col-lg-3 col-form-label">性别</label>
                  <div class="col-md-8 col-lg-9">
                    <select id="doctor_sex" class="form-select" name="doctor_sex">
                      {% if doctor.doctor_sex == '男' %}
                      <option selected>男</option>
                      <option>女</option>
                      {% else %}
                      <option>男</option>
                      <option selected>女</option>
                      {% endif %}
                    </select>

                  </div>
                </div>
                <div class="row mb-3">
                  <label for="doctor_age" class="col-md-4 col-lg-3 col-form-label">年龄</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="doctor_age" type="text" class="form-control" id="doctor_age" value="{{doctor.doctor_age}}">
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="email" class="col-md-4 col-lg-3 col-form-label">邮箱</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="email" type="text" class="form-control" id="email" value="{{doctor.email}}">
                  </div>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-primary" href="{% url 'adminApp:doctor_manage' %}?uid={{doctor.uid}}">保存</button>
                </div>
              </form><!-- End Profile Edit Form -->
            </div>
          </div><!-- End Bordered Tabs -->
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

IM_Sys/adminApp/templates/info_manage.html
{% extends "admin_base.html" %}
{% block title %}
健康档案管理
{% endblock %}

{% block subtitle %}
健康档案管理
{% endblock %}

{% block main %}
健康档案管理
{% endblock %}

{% block content %}
<section class="section profile">
  <div class="row">
    <section class="section">
      <div class="col-xl-12">
        <div class="card">
          <div class="card-body">
            <div class="card-title"></div>
            <div class="table-responsive">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>用户编号</th>
                    <th>姓名</th>
                    <th>身高</th>
                    <th>体重</th>
                    <th>药物过敏史</th>
                    <th>疾病史</th>
                    <th>是否残疾</th>
                    <th>常用药</th>
                    <th>操作</th>
                  </tr>

                </thead>
                <tbody>
                  {% for userinfo in userinfos %}
                  <tr>
                    <td>{{ userinfo.infoid }}</td>
                    <td>{{ userinfo.user_name }}</td>
                    <td>{{ userinfo.user_height }}</td>
                    <td>{{ userinfo.user_weight }}</td>
                    <td>{{ userinfo.allergy }}</td>
                    <td>{{ userinfo.illness }}</td>
                    <td>{{ userinfo.disability }}</td>
                    <td>{{ userinfo.common_drugs }}</td>
                    <td>
                      <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:ehi' userinfo.infoid %}">编辑</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>用户编号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>血糖</th>
                    <th>总胆固醇</th>
                    <th>甘油三酯</th>
                    <th>低压</th>
                    <th>高压</th>
                    <th>心率</th>
                    <th>操作</th>
                  </tr>
                </thead>
                <tbody>
                  {% for pEinfo in pEinfos %}
                  <tr>
                    <td>{{ pEinfo.PEid }}</td>
                    <td>{{ pEinfo.user_name }}</td>
                    <td>{{ pEinfo.user_sex }}</td>
                    <td>{{ pEinfo.blood_sugar }}</td>
                    <td>{{ pEinfo.total_cholesterol }}</td>
                    <td>{{ pEinfo.triglyceride }}</td>
                    <td>{{ pEinfo.minimum }}</td>
                    <td>{{ pEinfo.maximum }}</td>
                      <td>{{ pEinfo.heart_rate }}</td>

                    <td>
                      <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:ehi1' pEinfo.PEid %}">编辑</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>用户编号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>就诊科室</th>
                    <th>主诉</th>
                    <th>现病史</th>
                    <th>既往史</th>
                    <th>诊断</th>
                    <th>处方药</th>
                    <th>医嘱</th>
                  </tr>
                </thead>
                <tbody>
                  {% for visit in visits %}
                  <tr>
                    <td>{{ visit.vid }}</td>
                    <td>{{ visit.user_name }}</td>
                    <td>{{ visit.user_sex }}</td>
                    <td>{{ visit.department }}</td>
                    <td>{{ visit.chief_complaint }}</td>
                    <td>{{ visit.HPI }}</td>
                    <td>{{ visit.PH }}</td>
                    <td>{{ visit.diagnose }}</td>
                      <td>{{ visit.DA }}</td>



                    <td>
                      <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:ehi2' visit.vid %}">编辑</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>
{% endblock %}

IM_Sys/adminApp/templates/news_details-manage.html
{% extends "admin_base.html" %}
{% block title %}
健康新闻管理
{% endblock %}

{% block subtitle %}
健康资讯管理/新闻管理
{% endblock %}


{% block main %}健康新闻管理{% endblock %}

{% block content %}



<section class="section dashboard">
    <div class="row">
  
      <!-- Left side columns -->
      <div class="col-lg-12">
        <div class="row">
          <div class="card">
            <div class="card-body">
              <h2 class="text-center card-title">{{news.news_title}}</h2>
              <h6 class="text-center">{{news.c_time}}</h6>
              <p class="card-text">{{news.news_content}}</p>
            </div>
            <div class="text-center" style="margin-bottom: 20px;">
              <img src="{{news.news_img}}" class="card-img-bottom" style="width: 50%;">
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}

IM_Sys/adminApp/templates/patient_manage.html
{% extends "admin_base.html" %}
{% block title %}
普通用户管理
{% endblock %}

{% block subtitle %}
用户权限管理/普通用户管理
{% endblock %}


{% block main %}普通用户管理{% endblock %}

{% block content %}


<section class="section profile">
  <div class="row">


    <!--    个人基本信息记录修改 -->
    <section class="section">
      <div class="row">
        <div class="col-xl-12">

          <div class="card">
            <div class="card-body">
              <!-- <h5 class="card-title">
                <a class="btn btn-danger" href="#!"><i class="mdi mdi-window-close"></i> 批量注销</a>
              </h5> -->

              <div class="card-title"></div>
              <div class="table-responsive">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <!-- <th>
                        <label class="lyear-checkbox checkbox-primary">
                          <input type="checkbox" id="check-all"><span></span>
                        </label>
                      </th> -->
                      <th>用户编号</th>
                      <th>姓名</th>
                      <th>性别</th>
                      <th>年龄</th>
                      <th>邮箱</th>

                      <th>注册日期</th>
                      <th>状态</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for user in users %}

                    <tr>

                      <!-- <td>
                        <label class="lyear-checkbox checkbox-primary">
                          <input type="checkbox" name="ids[]" value="1"><span></span>
                        </label>
                      </td> -->
                      <td>{{user.uid}}</td>
                      <td>{{user.user_name}}</td>
                      <td>{{user.user_sex}}</td>
                      <td>{{user.user_age}}</td>
                      <td>{{user.email}}</td>

                      <td>{{user.c_time}}</td>
                      {% if user.states %}
                      <td>

                        正常
                      </td>
                      <td>
                        <div class="btn-group">
                          <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'adminApp:user_manage' %}?uid={{user.uid}}">注销</a>
                        </div>
                      <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'adminApp:user_manage2' %}?uid={{user.uid}}">编辑</a>
                      </td>
                      {% else %}
                      <td>

                        已注销
                      </td>
                      <td>
                        <div class="btn-group">
                          <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'adminApp:user_manage1' %}?uid={{user.uid}}">取消注销</a>
                        </div>
                      </td>



                      {% endif %}



                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>

</section>

{% endblock %}